#!/usr/bin/env node

// Concatenate the proto-grammar/*.abnf files (common + per-version deltas)
// into a single embedded grammar string in src/grammar.ts, so the published
// package carries its grammar without shipping the .abnf files separately.
// Run via: npm run embed  (or:  node embed-grammar.js)
//
// The Rust port carries the same text in rs/src/grammar.rs and is written
// here too, so one command keeps every runtime's copy in step. Go is the
// exception: go/grammar.go is written by its own `go generate` program
// (go/grammar_gen.go), which produces the identical string.

const fs = require('fs')
const path = require('path')

const GRAMMAR_DIR = path.join(__dirname, '..', 'proto-grammar')
const OUT = path.join(__dirname, 'src', 'grammar.ts')
// The Rust port is optional in a checkout that predates it, so the
// embedder skips it when rs/src is absent rather than failing.
const RS_DIR = path.join(__dirname, '..', 'rs', 'src')
const RS_OUT = path.join(RS_DIR, 'grammar.rs')

// common first (defines every base rule); deltas extend via `name =/ alt`.
const ORDER = ['common', 'proto2', 'proto3', 'edition-2023', 'edition-2024']

const parts = ORDER.map((name) => {
  const file = path.join(GRAMMAR_DIR, name + '.abnf')
  return `; ===== ${name}.abnf =====\n` + fs.readFileSync(file, 'utf8')
})
const grammar = parts.join('\n')

// Escape for a JS template literal (backslash, backtick, and ${).
const escaped = grammar
  .replace(/\\/g, '\\\\')
  .replace(/`/g, '\\`')
  .replace(/\$\{/g, '\\${')

const out =
  '/* Copyright (c) 2026 Richard Rodger and other contributors, MIT License */\n' +
  '\n' +
  '// GENERATED by embed-grammar.js from proto-grammar/*.abnf — do not edit.\n' +
  '// Run `npm run embed` after changing any .abnf file.\n' +
  '\n' +
  'export const grammarText = `\n' +
  escaped +
  '`\n'

fs.writeFileSync(OUT, out)
console.log('Embedded', ORDER.length, 'grammar files into', path.relative(__dirname, OUT))

// --- Rust embedding ---
//
// A leading newline then the parts joined by "\n", exactly as the
// TypeScript template literal and go/grammar_gen.go produce, so all three
// runtimes compile the same text. rs/tests/embed_test.rs holds that claim.
if (fs.existsSync(RS_DIR)) {
  // A Rust raw string ends at the first `"` followed by as many `#` as
  // opened it, so `r#"..."#` holds any text that does not contain the two
  // characters `"#` in that order. Nothing escapes inside one, which is
  // why the text is written verbatim rather than through an escape pass.
  if (grammar.includes('"#')) {
    console.error('Grammar contains \'"#\', incompatible with a r#"..."# literal')
    process.exit(1)
  }

  const rust =
    '/* Copyright (c) 2026 Richard Rodger and other contributors, MIT License */\n' +
    '\n' +
    '// GENERATED by ts/embed-grammar.js from proto-grammar/*.abnf — do not edit.\n' +
    '// Run `npm run embed` (from ts/) after changing any .abnf file.\n' +
    '\n' +
    '/// The embedded union ABNF grammar source (common + per-version\n' +
    '/// deltas). Rust counterpart of the TS `grammarText`\n' +
    '/// (ts/src/grammar.ts) and the Go `GrammarText` (go/grammar.go).\n' +
    'pub const GRAMMAR_TEXT: &str = r#"\n' +
    grammar +
    '"#;\n'

  fs.writeFileSync(RS_OUT, rust)
  console.log('Embedded', ORDER.length, 'grammar files into',
    path.relative(__dirname, RS_OUT))
} else {
  console.log('No Rust port at', path.relative(__dirname, RS_DIR), '- skipped')
}
