#!/usr/bin/env node

// Concatenate the proto-grammar/*.abnf files (common + per-version deltas)
// into a single embedded grammar string in src/grammar.ts, so the published
// package carries its grammar without shipping the .abnf files separately.
// Run via: npm run embed  (or:  node embed-grammar.js)

const fs = require('fs')
const path = require('path')

const GRAMMAR_DIR = path.join(__dirname, '..', 'proto-grammar')
const OUT = path.join(__dirname, 'src', 'grammar.ts')

// common first (defines every base rule); deltas extend via `name =/ alt`.
const ORDER = ['common', 'proto2', 'proto3', 'edition-2023', 'edition-2024']

const parts = ORDER.map((name) => {
  const file = path.join(GRAMMAR_DIR, name + '.abnf')
  return `; ===== ${name}.abnf =====\n` + fs.readFileSync(file, 'utf8')
})
const grammar = parts.join('\n')

// Escape for a JS template literal (backslash, backtick, and ${).
const escaped = grammar
  .replace(/\\/g, '\\\\')
  .replace(/`/g, '\\`')
  .replace(/\$\{/g, '\\${')

const out =
  '/* Copyright (c) 2026 Richard Rodger and other contributors, MIT License */\n' +
  '\n' +
  '// GENERATED by embed-grammar.js from proto-grammar/*.abnf — do not edit.\n' +
  '// Run `npm run embed` after changing any .abnf file.\n' +
  '\n' +
  'export const grammarText = `\n' +
  escaped +
  '`\n'

fs.writeFileSync(OUT, out)
console.log('Embedded', ORDER.length, 'grammar files into', path.relative(__dirname, OUT))
