//go:build ignore

/* Copyright (c) 2026 Richard Rodger and other contributors, MIT License */

// Command grammar_gen concatenates ../proto-grammar/*.abnf (common + the
// per-version deltas) into the embedded grammarText const in grammar.go, so
// the module carries its grammar without shipping the .abnf files. This is
// the Go counterpart of ts/embed-grammar.js and produces a byte-identical
// grammar string.
//
// Run:  go generate ./...   (or:  go run grammar_gen.go)
package main

import (
	"fmt"
	"os"
	"strconv"
	"strings"
)

// common first (defines every base rule); deltas extend via `name =/ alt`.
var order = []string{"common", "proto2", "proto3", "edition-2023", "edition-2024"}

func main() {
	parts := make([]string, 0, len(order))
	for _, name := range order {
		b, err := os.ReadFile("../proto-grammar/" + name + ".abnf")
		if err != nil {
			fmt.Fprintln(os.Stderr, "grammar_gen:", err)
			os.Exit(1)
		}
		parts = append(parts, "; ===== "+name+".abnf =====\n"+string(b))
	}
	// Matches embed-grammar.js: a leading newline then the parts joined by "\n".
	grammar := "\n" + strings.Join(parts, "\n")

	out := "/* Copyright (c) 2026 Richard Rodger and other contributors, MIT License */\n\n" +
		"// GENERATED by grammar_gen.go from ../proto-grammar/*.abnf — do not edit.\n" +
		"// Run `go generate ./...` after changing any .abnf file.\n\n" +
		"package tabnasproto\n\n" +
		"const grammarText = " + strconv.Quote(grammar) + "\n"

	if err := os.WriteFile("grammar.go", []byte(out), 0o644); err != nil {
		fmt.Fprintln(os.Stderr, "grammar_gen:", err)
		os.Exit(1)
	}
	fmt.Println("Embedded", len(order), "grammar files into grammar.go")
}
