/* Copyright (c) 2026 Richard Rodger and other contributors, MIT License */

// GENERATED by embed-grammar.js from proto-grammar/*.abnf — do not edit.
// Run `npm run embed` after changing any .abnf file.

export const grammarText = `
; ===== common.abnf =====
; @tabnas/proto — Protocol Buffers .proto IDL, common (union base).
; Structure only; lexical atoms are the engine's whole-word tokens:
;   TX = identifier   NR = number   ST = string   VL = true/false/null
; Whitespace and // and /* */ comments are ignored by the lexer.
; The grammar is a permissive superset of proto2 / proto3 / editions;
; version-specific legality is enforced in the descriptor walk.

proto          = [ syntaxOrEdition ] *topLevelDef

; protoc takes a string wherever it reads one as C does: adjacent literals
; are one string, concatenated (\`syntax = "pro" "to3";\`). Every string
; site below takes them, and the walk records what protoc records.
syntaxOrEdition = "syntax" "=" strLit *strLit ";"

topLevelDef    = importStmt / packageStmt / optionStmt / message / enumDef
               / service / extendStmt / emptyStmt

importStmt     = "import" [ "weak" / "public" ] strLit *strLit ";"
packageStmt    = "package" fullIdent ";"

optionStmt     = "option" optionName "=" constant ";"
optionName     = optionNamePart *( "." optionNamePart )
optionNamePart = ident / "(" [ "." ] fullIdent ")"

message        = "message" ident messageBody
messageBody    = "{" *messageElement "}"
messageElement = field / enumDef / message / optionStmt / oneof / mapField
               / extendStmt / extensions / reserved / emptyStmt

field          = [ label ] fieldType ident "=" fieldNumber [ fieldOptions ] ";"
label          = "required" / "optional" / "repeated"
fieldType      = messageType
fieldNumber    = NR
fieldOptions   = "[" fieldOption *( "," fieldOption ) "]"
fieldOption    = optionName "=" constant

oneof          = "oneof" ident "{" *oneofElement "}"
oneofElement   = optionStmt / oneofField / emptyStmt
oneofField     = fieldType ident "=" fieldNumber [ fieldOptions ] ";"

mapField       = "map" "<" fieldType "," fieldType ">" ident "=" fieldNumber
                 [ fieldOptions ] ";"

enumDef        = "enum" ident "{" *enumElement "}"
enumElement    = optionStmt / enumField / reserved / emptyStmt
enumField      = ident "=" [ "-" ] fieldNumber [ fieldOptions ] ";"

service        = "service" ident "{" *serviceElement "}"
serviceElement = optionStmt / rpc / emptyStmt
rpc            = "rpc" ident "(" [ "stream" ] messageType ")"
                 "returns" "(" [ "stream" ] messageType ")"
                 ( ";" / "{" *( optionStmt / emptyStmt ) "}" )

extendStmt     = "extend" messageType "{" *( field / emptyStmt ) "}"
extensions     = "extensions" ranges [ fieldOptions ] ";"
reserved       = "reserved" ( ranges / fieldNames ) ";"
ranges         = range *( "," range )
; Enum reserved ranges may be negative, so a range bound is signed.
range          = [ "-" ] NR [ "to" ( [ "-" ] NR / "max" ) ]
; Reserved names are string literals in proto2/proto3 and bare identifiers
; from edition 2023 on; the union accepts either (and a mix).
fieldNames     = reservedName *( "," reservedName )
reservedName   = strLit *strLit / ident

constant       = boolLit / fullIdent / signedNumber / signedIdent
               / strLit *strLit / messageValue
signedNumber   = [ "-" / "+" ] NR
; \`-inf\` / \`-nan\`: a negated identifier constant. Tried after signedNumber
; so \`-33\` still lexes as a number.
signedIdent    = "-" fullIdent
boolLit        = VL
messageValue   = "{" *messageValueEntry "}"
; Text format writes a string value as one or more adjacent literals and
; concatenates them: \`a: "foo" "bar"\`. The first alternative takes two or
; more, so a single literal is a \`constant\`, as any other value is.
;
; protoc's parser does not read an aggregate: it records the text between
; the braces, and text format reads it once the option's type is known.
; The second alternative takes two forms of that text format the first
; does not: a repeated field's values as a list, \`a: [1, 2]\`, and a
; message in angle brackets, \`a < b: 1 >\`. Two more reach these rules as
; plain identifiers, because inside an aggregate the plugin's lexer reads
; them as text format does (ts/src/aggregate.ts): a word the grammar
; spells as a keyword (\`message: optional\`), and a field named by an
; extension or an Any type URL (\`[x.y]: 1\`,
; \`[type.googleapis.com/x.Y] { a: 1 }\`).
messageValueEntry = ident [ ":" ] ( strLit 1*strLit / constant ) [ "," / ";" ]
messageValueEntry =/ ident [ ":" ] ( listValue / angleValue ) [ "," / ";" ]
listValue      = "[" [ ( constant / angleValue ) *( "," ( constant / angleValue ) ) ] "]"
angleValue     = "<" *messageValueEntry ">"

messageType    = [ "." ] fullIdent
fullIdent      = ident *( "." ident )
ident          = TX
strLit         = ST
emptyStmt      = ";"

; ===== proto2.abnf =====
; proto2 deltas: groups are proto2-only (deprecated). Labels (required/
; optional/repeated), extend, and extensions live in common (the permissive
; union); the descriptor walk enforces what each version actually allows.
messageElement =/ groupField
; A group is also a legal oneof member (\`oneof foo { group D = 4 {…} }\`).
oneofElement   =/ groupField
groupField     = [ label ] "group" ident "=" fieldNumber messageBody

; ===== proto3.abnf =====
; proto3 deltas: none. proto3's surface syntax is the common base
; (implicit label via the optional [ label ], plus the "optional" keyword).
; Version legality (no required, no group) is enforced in the walk.

; ===== edition-2023.abnf =====
; edition 2023 deltas: the file may open with an \`edition = "2023";\`
; declaration instead of \`syntax = ...\`.
syntaxOrEdition =/ editionDecl
editionDecl     = "edition" "=" strLit *strLit ";"

; ===== edition-2024.abnf =====
; edition 2024 deltas: \`import option "...";\` and symbol visibility
; (export / local) on message and enum declarations.
importStmt      =/ "import" "option" strLit *strLit ";"
topLevelDef     =/ symbolVisibility message / symbolVisibility enumDef
messageElement  =/ symbolVisibility message / symbolVisibility enumDef
symbolVisibility = "export" / "local"
; \`export\` and \`local\` are contextual: they are only visibility modifiers
; ahead of \`message\`/\`enum\`, and stay usable as ordinary name components
; (\`local.pkg.SomeMessage\`). The union grammar lexes them as keywords, so
; give fullIdent an alternative that may open with one.
fullIdent       =/ symbolVisibility *( "." ident )
`
