/* Copyright (c) 2026 Richard Rodger and other contributors, MIT License */

// GENERATED by embed-grammar.js from proto-grammar/*.abnf — do not edit.
// Run `npm run embed` after changing any .abnf file.

export const grammarText = `
; ===== common.abnf =====
; @tabnas/proto — Protocol Buffers .proto IDL, common (union base).
; Structure only; lexical atoms are the engine's whole-word tokens:
;   TX = identifier   NR = number   ST = string   VL = true/false/null
; Whitespace and // and /* */ comments are ignored by the lexer.
; The grammar is a permissive superset of proto2 / proto3 / editions;
; version-specific legality is enforced in the descriptor walk.

proto          = [ syntaxOrEdition ] *topLevelDef

syntaxOrEdition = "syntax" "=" strLit ";"

topLevelDef    = importStmt / packageStmt / optionStmt / message / enumDef
               / service / extendStmt / emptyStmt

importStmt     = "import" [ "weak" / "public" ] strLit ";"
packageStmt    = "package" fullIdent ";"

optionStmt     = "option" optionName "=" constant ";"
optionName     = optionNamePart *( "." optionNamePart )
optionNamePart = ident / "(" [ "." ] fullIdent ")"

message        = "message" ident messageBody
messageBody    = "{" *messageElement "}"
messageElement = field / enumDef / message / optionStmt / oneof / mapField
               / extendStmt / extensions / reserved / emptyStmt

field          = [ label ] fieldType ident "=" fieldNumber [ fieldOptions ] ";"
label          = "required" / "optional" / "repeated"
fieldType      = messageType
fieldNumber    = NR
fieldOptions   = "[" fieldOption *( "," fieldOption ) "]"
fieldOption    = optionName "=" constant

oneof          = "oneof" ident "{" *oneofElement "}"
oneofElement   = optionStmt / oneofField / emptyStmt
oneofField     = fieldType ident "=" fieldNumber [ fieldOptions ] ";"

mapField       = "map" "<" fieldType "," fieldType ">" ident "=" fieldNumber
                 [ fieldOptions ] ";"

enumDef        = "enum" ident "{" *enumElement "}"
enumElement    = optionStmt / enumField / reserved / emptyStmt
enumField      = ident "=" [ "-" ] fieldNumber [ fieldOptions ] ";"

service        = "service" ident "{" *serviceElement "}"
serviceElement = optionStmt / rpc / emptyStmt
rpc            = "rpc" ident "(" [ "stream" ] messageType ")"
                 "returns" "(" [ "stream" ] messageType ")"
                 ( ";" / "{" *( optionStmt / emptyStmt ) "}" )

extendStmt     = "extend" messageType "{" *( field / emptyStmt ) "}"
extensions     = "extensions" ranges [ fieldOptions ] ";"
reserved       = "reserved" ( ranges / fieldNames ) ";"
ranges         = range *( "," range )
range          = NR [ "to" ( NR / "max" ) ]
fieldNames     = strLit *( "," strLit )

constant       = boolLit / fullIdent / signedNumber / strLit / messageValue
signedNumber   = [ "-" / "+" ] NR
boolLit        = VL
messageValue   = "{" *messageValueEntry "}"
messageValueEntry = ident [ ":" ] constant [ "," / ";" ]

messageType    = [ "." ] fullIdent
fullIdent      = ident *( "." ident )
ident          = TX
strLit         = ST
emptyStmt      = ";"

; ===== proto2.abnf =====
; proto2 deltas: groups are proto2-only (deprecated). Labels (required/
; optional/repeated), extend, and extensions live in common (the permissive
; union); the descriptor walk enforces what each version actually allows.
messageElement =/ groupField
groupField     = [ label ] "group" ident "=" fieldNumber messageBody

; ===== proto3.abnf =====
; proto3 deltas: none. proto3's surface syntax is the common base
; (implicit label via the optional [ label ], plus the "optional" keyword).
; Version legality (no required, no group) is enforced in the walk.

; ===== edition-2023.abnf =====
; edition 2023 deltas: the file may open with an \`edition = "2023";\`
; declaration instead of \`syntax = ...\`.
syntaxOrEdition =/ editionDecl
editionDecl     = "edition" "=" strLit ";"

; ===== edition-2024.abnf =====
; edition 2024 deltas: \`import option "...";\` and symbol visibility
; (export / local) on message and enum declarations.
importStmt      =/ "import" "option" strLit ";"
topLevelDef     =/ symbolVisibility message / symbolVisibility enumDef
messageElement  =/ symbolVisibility message / symbolVisibility enumDef
symbolVisibility = "export" / "local"
`
